API_Capstone/API_Capstone/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API_Capstone.Models.ApiModels;
using API_Capstone.Models.DALModels;
using API_Capstone.Models.ViewModels;
using API_Capstone.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace API_Capstone.Controllers
{
    public class RecipeController : Controller
    {
        private readonly RecipesDBContext _recipesDbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RecipeClient _RecipeClient;

        public RecipeController(RecipesDBContext recipesDbContext, UserManager<IdentityUser> userManager, RecipeClient RecipeClient)
        {
            _recipesDbContext = recipesDbContext;
            _userManager = userManager;
            _RecipeClient = RecipeClient;
        }
        public async Task<IActionResult> Index(int pageNumber)
        {
            var model = new RecipeSearchViewModel();

            model.Recipes = new List<Result>();

            var response = await _RecipeClient.GetAllRecipes(pageNumber);



            foreach (var recipe in response.results)
            {
                model.Recipes.Add(recipe);
            }

            model.currentPageNumber = pageNumber;
            model.nextPageNumber = pageNumber + 1;
            model.previousPageNumber = pageNumber - 1;

            return View(model);
        }
        public async Task<IActionResult> Search(string searchInfo, string searchType)
        {
            var pageNumber = 1;

            var model = new RecipeSearchViewModel();

            model.Recipes = new List<Result>();

            if (!String.IsNullOrEmpty(searchInfo))
            {
                if (searchType == "AllRecipes")
                {
                    do
                    {
                        var response = await _RecipeClient.GetAllRecipes(pageNumber);
                        foreach (var recipe in response.results)
                        {

                            if (recipe.title.Contains(searchInfo, StringComparison.OrdinalIgnoreCase))
                            {
                                
                                model.Recipes.Add(recipe);
                            }
                        }

                        pageNumber = pageNumber + 1;

                    }
                    while (pageNumber < 100);
                }


            }
            return View(model);
        }
        public IActionResult AddToFavorites(string Title, string Href, string Ingredients, string Thumbnail)
        {
            var dbModel = new RecipeFavoritesDAL();

            dbModel.Title = Title;
            dbModel.Href = Href;
            dbModel.Ingredients = Ingredients;
            dbModel.Thumbnail = Thumbnail;


            dbModel.UserId = _userManager.GetUserId(User);
        _recipesDbContext.FavoriteRecipes.Add(dbModel);
            _recipesDbContext.SaveChanges();

            return View();
        }

        [Authorize]
        public IActionResult ViewFavorites()
        {
            var recipes = _recipesDbContext.FavoriteRecipes.Where(recipe=> recipe.UserId == _userManager.GetUserId(User))
                .Select(recipeFavoritesDAL => new RecipeVM() 
                { Title = recipeFavoritesDAL.Title , Href = recipeFavoritesDAL.Href, Ingredients = recipeFavoritesDAL.Ingredients, Thumbnail= recipeFavoritesDAL.Thumbnail })
                .ToList();
            var viewModel = new AddRecipeResultViewModel();
            viewModel.recipe = recipes;
            return View(viewModel);
        }   
    
        //    }    //public async Task<IActionResult> ViewFavorties()
        //{
        //    var model = new RecipeSearchViewModel();
        //    model.Recipes = new List<Result>();
        //    var tempRecipe = new Result();
        //    var listOfRecipes = model.Recipes;
        //    foreach (var recipe in _recipesDbContext.FavoriteRecipes)
        //    {
        //       await Search(recipe.Title, "AllRecipes", _userManager.GetUserId(User));
                

        //    }
        //    return View();
        //}

        //public async Task<IActionResult> Search(string recipeTitle, string searchType, string userId)
        //{
        //    var pageNumber = 1;


        //    var model = new RecipeSearchViewModel();

        //    model.Recipes = new List<Result>();

        //    if (!String.IsNullOrEmpty(recipeTitle))
        //    {
        //        do
        //        {
        //            var response = await _RecipeClient.GetAllRecipes(pageNumber);
        //            foreach (var recipe in response.results)
        //            {

        //                if (recipe.title.Contains(recipeTitle, StringComparison.OrdinalIgnoreCase))
        //                {

        //                    model.Recipes.Add(recipe);
        //                }
        //            }

        //            pageNumber = pageNumber + 1;

        //        }
        //        while (pageNumber < 1000);



        //    return (IActionResult)model.Recipes;
        //TODO: return single recipe, send to view favorite, save to list there
        //}
    }
}

API_Capstone/API_Capstone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - API_Capstone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">API_Capstone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index" asp-route-pagenumber="1">Test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Search">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="ViewFavorites">View your favorite numms</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - API_Capstone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>